import { type Component } from 'vue';

export interface IIncident {
  incidentId: string,
  action?: string,
  cameraId: string | number,
  cameraName: string,
  itsId: string,
  uniqueIncidentId: string,
  generatedId: string,
  severityLevel: string,
  dateTime: string,
  coordinates: string,
  status: string,
  incidentNumber: string,
  icon: Component,
  image: string,
  incidentType: string,
  scroll?: boolean // for fake incident in incidents list (use in virtual scroll only),
  incidentGroup?: string,
  incidentSubgroup?: string,
  roadClosures?: string,
  locationSpecification?: string,
  staticNature?: string,
  address?: string,
  objects?: string,
  direction?: string,
  isViewed?: boolean,
}
